/*!
 * Road to LA — data.js
 * Todo el contenido editable vive aquí: configuración, fotos, días y lugares.
 * Para cambiar una canción, un dato o una foto, edita este archivo y vuelve a subirlo.
 *
 * Enlaces de música: por defecto abren una búsqueda exacta en YouTube y Spotify
 * (nunca se rompen). Si prefieres el enlace directo a una pista, reemplaza
 * youtubeUrl o spotifyUrl del día por el enlace que copies desde la app.
 */
(function (root) {
  'use strict';

  const CONFIG = {
    appName: 'Road to LA',
    startDate: '2026-10-02',          // DAY 35
    departureDate: '2026-11-06',      // THE DAY
    timeZone: 'America/Costa_Rica',   // UTC-6, sin horario de verano
    utcOffsetFallbackMinutes: -360,
    destinationTimeZone: 'America/Los_Angeles',
    origin: { code: 'SJO', city: 'San José', country: 'Costa Rica' },
    destination: { code: 'LAX', city: 'Los Ángeles', country: 'California' },
    distanceKm: 4380,
    push: {
      // Web Push (opcional): pega aquí tu clave pública VAPID. Ver README.
      vapidPublicKey: '',
      dailyHour: 8,
    },
  };

  const yt = (q) => 'https://www.youtube.com/results?search_query=' + encodeURIComponent(q);
  const sp = (q) => 'https://open.spotify.com/search/' + encodeURIComponent(q);
  const wiki = (title) => 'https://en.wikipedia.org/wiki/' + title;
  const music = (song, artist, query) => ({
    song,
    artist,
    youtubeUrl: yt(query || song + ' ' + artist),
    spotifyUrl: sp(query || song + ' ' + artist),
  });

  const CATEGORIES = {
    lugares: { label: 'Lugares', icon: 'pin' },
    cine: { label: 'Cine', icon: 'film' },
    musica: { label: 'Música', icon: 'note' },
    parques: { label: 'Parques', icon: 'wheel' },
    costa: { label: 'Costa', icon: 'wave' },
    sabores: { label: 'Sabores', icon: 'taco' },
    historia: { label: 'Historia', icon: 'hourglass' },
    viaje: { label: 'Viaje', icon: 'plane' },
  };

  // Fotos de Wikimedia Commons (licencias libres). Cada día prueba sus fotos en
  // orden; si ninguna carga, queda la ilustración propia de la escena.
  const PHOTOS = {
    skyline: { file: 'LA Skyline Mountains2.jpg', author: 'Nserrano', license: null, alt: 'Los rascacielos del centro de Los Ángeles con las montañas al fondo' },
    downtownSunset: { file: 'LosAngeles06.jpg', author: 'Thomas Pintaric', license: 'GFDL', alt: 'El centro de Los Ángeles media hora antes del atardecer' },
    panorama: { file: 'Los Angeles Pollution.jpg', author: 'Diliff', license: 'CC BY 2.5', alt: 'Panorámica de Los Ángeles y el Observatorio Griffith desde las colinas de Hollywood' },
    griffith: { file: 'Griffith observatory 2006.jpg', author: 'Matthew Field', license: 'CC BY-SA 3.0', alt: 'La fachada del Observatorio Griffith sobre las colinas de Hollywood' },
    ferrisWheel: { file: 'Santa Monica Ferris Wheel.jpg', author: 'Dwaynewilbert', license: 'CC BY-SA 4.0', alt: 'La noria de Pacific Park en el muelle de Santa Mónica' },
    signWolf: { file: 'Hollywood Sign (Zuschnitt).jpg', author: 'Thomas Wolf, www.foto-tw.de', license: 'CC BY-SA 3.0', alt: 'El letrero de Hollywood en el monte Lee' },
    signBoereck: { file: 'HollywoodSign.jpg', author: 'boereck', license: 'CC BY-SA 2.0', alt: 'El letrero de Hollywood sobre las colinas' },
    signDillon: { file: 'Hollywood Sign close up 2006.jpg', author: 'Mike Dillon', license: 'CC BY-SA 2.5', alt: 'Vista cercana del letrero de Hollywood' },
    castle2013: { file: 'Sleeping Beauty Castle Disneyland Anaheim 2013.jpg', author: 'Tuxyso', license: 'CC BY-SA 3.0', alt: 'El castillo de la Bella Durmiente en Disneyland' },
    castle2013b: { file: 'Sleeping Beauty Castle Disneyland Anaheim 2013.jpeg', author: 'Tuxyso', license: 'CC BY-SA 3.0', alt: 'El castillo de la Bella Durmiente en Disneyland' },
    castle2005: { file: 'Sleepingbeautycastle50.jpg', author: 'Lyght', license: 'CC BY-SA 3.0', alt: 'El castillo de Disneyland decorado para los 50 años del parque' },
    psycho: { file: 'Psycho House-Universal Studios-Hollywood-California4481.JPG', author: 'Diego Delso', license: null, alt: 'La casa de la película Psycho en el backlot de Universal Studios Hollywood' },
    starCooper: { file: 'Los Angeles (California, USA), Hollywood Boulevard, Gary Cooper -- 2012 -- 4981.jpg', author: 'Dietmar Rabich', license: 'CC BY-SA 4.0', alt: 'La estrella de Gary Cooper en el Paseo de la Fama de Hollywood' },
    starLennon: { file: 'Los Angeles (California, USA), Hollywood Boulevard, John Lennon -- 2012 -- 4990.jpg', author: 'Dietmar Rabich', license: 'CC BY-SA 4.0', alt: 'La estrella de John Lennon en el Paseo de la Fama de Hollywood' },
    starStewart: { file: 'Stewart walk of fame.jpg', author: 'CChen', license: 'CC BY-SA 3.0', alt: 'La estrella de James Stewart en el Paseo de la Fama' },
    route66: { file: 'Amboy (California, USA), Hist. Route 66 -- 2012 -- 1.jpg', author: 'Dietmar Rabich', license: 'CC BY-SA 4.0', alt: 'La Ruta 66 histórica a su paso por Amboy, en el desierto de Mojave' },
    amboy: { file: 'Amboy (California, USA) -- 2012 -- 4.jpg', author: 'Dietmar Rabich', license: 'CC BY-SA 4.0', alt: 'Amboy, un pueblo de la Ruta 66 en el desierto de Mojave' },
    smBeach: { file: 'Los Angeles (California, USA), Santa Monica Beach -- 2012 -- 5308.jpg', author: 'Dietmar Rabich', license: 'CC BY-SA 4.0', alt: 'La playa de Santa Mónica' },
    veniceTower: { file: 'Venice Beach Lifeguard Tower.JPG', author: 'Adrian104', license: null, alt: 'Una torre de salvavidas en Venice Beach' },
    hollywood1922: { file: 'Hollywood-Studios-1922.jpg', author: 'Autor desconocido, Biblioteca Pública de Los Ángeles', license: 'dominio público', alt: 'Estudios de cine de Hollywood en 1922' },
  };

  // ---------------------------------------------------------------------------
  // Los 36 días: DAY 35 (2 de octubre) → DAY 0 (6 de noviembre).
  // ---------------------------------------------------------------------------
  const countdownDays = [
    {
      date: '2026-10-02', dayNumber: 35, category: 'lugares', scene: 'skyline',
      title: 'Opening Night', theme: 'La primera noche del camino',
      description: 'Así empiezan las buenas películas: con la ciudad de noche, vista desde lejos. Durante 35 días, Los Ángeles se va a acercar una escena a la vez. Hoy solo toca mirarla y empezar a imaginarte ahí.',
      ...music('Midnight City', 'M83'),
      songWhy: 'Anthony Gonzalez, el francés detrás de M83, se mudó a Los Ángeles para hacer el disco donde salió esta canción. Suena a autopista iluminada a medianoche: la banda sonora perfecta para arrancar.',
      fact: 'Los Ángeles es la segunda ciudad más poblada de Estados Unidos, y su condado, con casi 10 millones de habitantes, es el más poblado del país: tiene más gente que la mayoría de los estados.',
      factSource: wiki('Los_Angeles_County,_California'),
      place: { name: 'Downtown Los Angeles', area: 'El centro', note: 'El grupo de rascacielos de todas las postales nocturnas. De noche se enciende como un tablero de control.', query: 'Downtown Los Angeles' },
      movie: { title: 'Collateral', year: 2004, note: 'Michael Mann rodó buena parte de la película en video digital para captar la luz real de las calles de LA de noche.' },
      tip: 'Crea hoy una playlist llamada “Road to LA” y añade la canción de cada día. El 6 de noviembre vas a tener la banda sonora completa del viaje.',
      image: ['downtownSunset', 'panorama'],
    },
    {
      date: '2026-10-03', dayNumber: 34, category: 'historia', scene: 'sunset',
      title: 'California Dreamin’', theme: 'El nombre que salió de una novela',
      description: 'Antes de ser un estado, California fue una idea: una isla imaginaria llena de oro. Hoy el viaje empieza por el nombre, que tiene más de español de lo que parece.',
      ...music('California Dreamin’', 'The Mamas & the Papas'),
      songWhy: 'John y Michelle Phillips la escribieron en 1963, durante un invierno helado en Nueva York, soñando con el sol de California. Es lo mismo que estás haciendo tú, pero desde Costa Rica.',
      fact: 'El nombre “California” viene de Las sergas de Esplandián, una novela de caballería española publicada hacia 1510 por Garci Rodríguez de Montalvo. Describía una isla mítica, gobernada por la reina Calafia, donde el único metal era el oro.',
      factSource: wiki('Las_sergas_de_Esplandián'),
      place: { name: 'California', area: 'El estado', note: 'Es el estado más poblado de Estados Unidos y el tercero más grande, después de Alaska y Texas.', query: 'California' },
      movie: null,
      tip: 'Revisa hoy la vigencia de tu pasaporte y de tu visa, y guarda fotos de ambos (y de tus reservas) en el teléfono y en la nube.',
      image: [],
    },
    {
      date: '2026-10-04', dayNumber: 33, category: 'lugares', scene: 'lights',
      title: 'The Sign', theme: 'Nueve letras en la montaña',
      description: 'Es probablemente el letrero más famoso del planeta, y nació como un anuncio de bienes raíces. Verlo en persona tiene algo de confirmar que la película era real.',
      ...music('Hollywood Nights', 'Bob Seger & The Silver Bullet Band'),
      songWhy: 'Un chico del Medio Oeste que se deslumbra con las colinas de Hollywood. Pura energía de llegar a un lugar que te queda grande, en el buen sentido.',
      fact: 'Se levantó en 1923 con la palabra HOLLYWOODLAND, como publicidad de una urbanización. En 1949 le quitaron “LAND”. Cada letra mide unos 13 metros de alto.',
      factSource: wiki('Hollywood_Sign'),
      place: { name: 'Monte Lee', area: 'Hollywood Hills', note: 'El letrero está en la ladera del monte Lee, dentro de Griffith Park.', query: 'Hollywood Sign' },
      movie: null,
      tip: 'Las letras están cercadas y vigiladas: no se pueden tocar. Para la foto clásica, prueba desde Griffith Observatory o desde Lake Hollywood Park.',
      image: ['signBoereck', 'signDillon'],
    },
    {
      date: '2026-10-05', dayNumber: 32, category: 'musica', scene: 'pier',
      title: 'Surf City', theme: 'El sonido de la costa',
      description: 'A principios de los 60, California inventó una forma de sonar: guitarras brillantes, armonías y tablas de surf. Hoy es día de mar, aunque sea con audífonos.',
      ...music('Surf City', 'Jan and Dean'),
      songWhy: 'La coescribió Brian Wilson, de los Beach Boys, y en 1963 llegó al número uno en Estados Unidos. Es la postal sonora de la costa californiana.',
      fact: 'Surfrider Beach, en Malibú, fue nombrada en 2010 la primera World Surfing Reserve del mundo, por la calidad de sus olas y su lugar en la historia del surf.',
      factSource: wiki('Surfrider_Beach'),
      place: { name: 'Surfrider Beach', area: 'Malibú', note: 'Junto al muelle de Malibú. Aunque no surfees, ver las olas desde el muelle vale la pena.', query: 'Surfrider Beach Malibu' },
      movie: { title: 'Gidget', year: 1959, note: 'La película que llevó la cultura surf de Malibú al gran público.' },
      tip: 'El Pacífico de California es frío: en noviembre el agua suele andar entre 16 y 18 °C. Si te metes, que sea rápido.',
      image: ['smBeach'],
    },
    {
      date: '2026-10-06', dayNumber: 31, category: 'costa', scene: 'road',
      title: 'Pacific Coast Highway', theme: 'La carretera junto al mar',
      description: 'Hay carreteras que conectan lugares y carreteras que son el lugar. La PCH es de las segundas: acantilados, océano a un lado y la sensación de estar dentro de un comercial de carros.',
      ...music('Ventura Highway', 'America'),
      songWhy: 'Es de 1972 y suena a manejar con la ventana abierta junto al mar. Su título habla de la ruta costera de Ventura, al norte de LA.',
      fact: 'La State Route 1, la PCH en el tramo de Los Ángeles, recorre casi toda la costa de California: unos 1.050 km. Es la carretera estatal más larga de California.',
      factSource: wiki('California_State_Route_1'),
      place: { name: 'PCH en Malibú', area: 'Malibú', note: 'El tramo entre Santa Mónica y Malibú es el más fácil de recorrer desde LA, con el océano siempre a la vista.', query: 'Pacific Coast Highway Malibu' },
      movie: null,
      tip: 'Si algún día la recorres en carro, ve de norte a sur: así tu carril es el del lado del mar.',
      image: [],
    },
    {
      date: '2026-10-07', dayNumber: 30, category: 'viaje', scene: 'sunset',
      title: 'The Map', theme: 'Un mes para entender la ciudad',
      milestone: { key: '30', label: '30 Days to LA', message: 'Un mes. Desde hoy, el viaje tiene calendario propio.' },
      description: 'Faltan 30 días: buen momento para ver el mapa completo. Los Ángeles no es una ciudad, es una constelación de ciudades unidas por autopistas, y entender eso cambia cómo se planea un viaje.',
      story: 'Imagínala desde el aire: la costa a un lado, las colinas de Hollywood al centro, el Valle detrás de las montañas y, muy al sur, Anaheim. Cada uno de tus seis lugares vive en un punto distinto de ese mapa. Planear por zonas es la diferencia entre ver LA y verla desde el tráfico.',
      ...music('West Coast', 'Lana Del Rey'),
      songWhy: 'Lenta, cálida y un poco melancólica, como la costa oeste al final de la tarde. A un mes del viaje, la costa ya empieza a llamar.',
      fact: 'Disneyland no está en Los Ángeles: está en Anaheim, en el condado de Orange, a unos 40 km del centro de LA. Santa Mónica, Beverly Hills y West Hollywood también son ciudades independientes.',
      factSource: wiki('Greater_Los_Angeles'),
      place: { name: 'Los Ángeles por zonas', area: 'Costa, Hollywood, el Valle y Anaheim', note: 'Costa: Santa Mónica y Venice. Centro-norte: Hollywood y Griffith. El Valle: Universal. Condado de Orange: Disneyland y California Adventure.', query: 'Los Angeles' },
      movie: null,
      tip: 'Agrupa tus días por zona: la costa un día, Hollywood y Griffith otro, Universal otro y Anaheim para los parques de Disney. El tráfico decide más que el mapa.',
      image: ['skyline'],
    },
    {
      date: '2026-10-08', dayNumber: 29, category: 'lugares', scene: 'observatory',
      title: 'Griffith Observatory', theme: 'La ciudad desde las estrellas',
      description: 'Un observatorio art déco en lo alto de una colina, con telescopios gratuitos y la mejor vista de LA. Es de esos lugares donde la ciudad se ve completa, de punta a punta.',
      ...music('Rocket Man', 'Elton John'),
      songWhy: 'Espacio, estrellas y nostalgia. Además, Elton John despegó en Estados Unidos con sus conciertos de 1970 en el Troubadour de West Hollywood, a pocos kilómetros de aquí.',
      fact: 'Abrió el 14 de mayo de 1935 en terrenos que Griffith J. Griffith donó a la ciudad en 1896. Su idea era que cualquier persona pudiera mirar por un telescopio, y la entrada al edificio sigue siendo gratuita.',
      factSource: wiki('Griffith_Observatory'),
      place: { name: 'Griffith Observatory', area: 'Griffith Park, Los Feliz', note: 'Sus terrazas miran al letrero de Hollywood por un lado y al centro de LA por el otro.', query: 'Griffith Observatory' },
      movie: { title: 'Rebel Without a Cause', year: 1955, note: 'Hay un busto de James Dean en el observatorio en homenaje a la película. También aparece en La La Land (2016).' },
      tip: 'Cierra los lunes. Llega antes del atardecer: ves la ciudad de día, el sunset y luego las luces encendiéndose. En noches despejadas suele haber telescopios públicos.',
      image: ['griffith'],
    },
    {
      date: '2026-10-09', dayNumber: 28, category: 'sabores', scene: 'skyline',
      title: 'Taco Truck Night', theme: 'LA se come en la calle',
      description: 'En Los Ángeles, algunos de los mejores platos no están en restaurantes: están en un camión estacionado en una esquina. Viernes de tacos, aunque sea en tu imaginación.',
      ...music('Tequila', 'The Champs'),
      songWhy: 'La grabaron músicos de Los Ángeles en 1958 y ganó en la primera edición de los Grammy. Casi sin letra: puro ritmo de fiesta.',
      fact: 'En 2008, el chef Roy Choi lanzó Kogi, un camión de tacos coreanos que anunciaba su ubicación por Twitter. Su éxito encendió la fiebre de los food trucks gourmet en Estados Unidos.',
      factSource: wiki('Roy_Choi'),
      place: { name: 'Grand Central Market', area: 'Downtown LA', note: 'Mercado techado abierto en 1917, con puestos de comida de todo el mundo bajo el mismo techo.', query: 'Grand Central Market Los Angeles' },
      movie: { title: 'Chef', year: 2014, note: 'Jon Favreau contó con Roy Choi como asesor para esta película sobre un food truck.' },
      tip: 'En Estados Unidos el precio que ves no incluye impuesto: se suma al pagar. En restaurantes con servicio a la mesa, la propina habitual va del 15 % al 20 %.',
      image: [],
    },
    {
      date: '2026-10-10', dayNumber: 27, category: 'cine', scene: 'lights',
      title: 'Walk of Fame', theme: 'Una avenida de estrellas',
      description: 'Cuadras y cuadras de estrellas de terrazo rosado con nombres que conoces desde siempre. Es turístico, sí, y aun así emociona encontrar el nombre que buscabas.',
      ...music('Hooray for Hollywood', 'Doris Day'),
      songWhy: 'Johnny Mercer y Richard Whiting la escribieron para la película Hollywood Hotel (1937) y se volvió el himno no oficial de Hollywood: suena una y otra vez en los Oscar.',
      fact: 'Hay más de 2.700 estrellas en cinco categorías: cine, televisión, música, radio y teatro en vivo. Solo una persona tiene estrella en las cinco: el cantante y actor Gene Autry.',
      factSource: wiki('Hollywood_Walk_of_Fame'),
      place: { name: 'Hollywood Boulevard y Vine Street', area: 'Hollywood', note: 'Las estrellas recorren el bulevar de este a oeste y bajan por Vine Street.', query: 'Hollywood Walk of Fame' },
      movie: null,
      tip: 'Busca antes en walkoffame.com dónde está la estrella de alguien que te importe. Caminar con un objetivo convierte la avenida en una búsqueda del tesoro.',
      image: ['starCooper', 'starStewart'],
    },
    {
      date: '2026-10-11', dayNumber: 26, category: 'musica', scene: 'neon',
      title: 'Sunset Boulevard', theme: 'De Downtown al Pacífico',
      description: 'Una sola calle cuenta casi toda la historia de LA: empieza en el centro, cruza Hollywood, se vuelve el Sunset Strip de los clubes de rock y termina frente al océano.',
      ...music('L.A. Woman', 'The Doors'),
      songWhy: 'The Doors se formaron en Los Ángeles en 1965 y en 1966 fueron la banda de la casa en el Whisky a Go Go, en pleno Sunset Strip.',
      fact: 'Sunset Boulevard mide unos 35 km: va desde el centro de Los Ángeles hasta la Pacific Coast Highway, junto al mar.',
      factSource: wiki('Sunset_Boulevard'),
      place: { name: 'Sunset Strip', area: 'West Hollywood', note: 'El tramo de clubes y carteleras gigantes donde nació buena parte del rock de la costa oeste.', query: 'Sunset Strip West Hollywood' },
      movie: { title: 'Sunset Boulevard', year: 1950, note: 'Billy Wilder la ambientó en una mansión de esta calle: una vieja estrella del cine mudo que no acepta que su época terminó. Ganó tres Oscar.' },
      tip: 'Si recorres Sunset hacia el oeste al final de la tarde, vas literalmente en dirección al atardecer.',
      image: [],
    },
    {
      date: '2026-10-12', dayNumber: 25, category: 'parques', scene: 'fireworks',
      title: 'Día Disneyland', theme: 'El parque que Walt vio construir',
      description: 'Hoy es el primer gran día de parques, aunque sea imaginado. Disneyland es el original: el único parque de Disney que Walt Disney vio construir y caminó en persona.',
      story: 'Imagina la entrada: pasas bajo las vías del tren, sales a Main Street, U.S.A. y al fondo aparece el castillo. Es más pequeño de lo que esperas, y ese es justamente el truco. Al cruzarlo hacia Fantasyland suena la canción de hoy.',
      ...music('When You Wish Upon a Star', 'Cliff Edwards'),
      songWhy: 'Es la voz de Pepito Grillo en Pinocho (1940) y ganó el Oscar a mejor canción. En Disneyland se escucha al atravesar el castillo hacia Fantasyland.',
      fact: 'Disneyland abrió el 17 de julio de 1955. El castillo de la Bella Durmiente mide 23 metros y usa perspectiva forzada, con piezas más grandes abajo y más pequeñas arriba, para parecer más alto.',
      factSource: wiki('Sleeping_Beauty_Castle'),
      place: { name: 'Main Street, U.S.A.', area: 'Disneyland, Anaheim', note: 'Sobre la estación de bomberos está el apartamento de Walt Disney: una lámpara se mantiene encendida en la ventana en su honor.', query: 'Main Street USA Disneyland' },
      movie: { title: 'Saving Mr. Banks', year: 2013, note: 'Tom Hanks interpreta a Walt Disney, y la película incluye escenas filmadas dentro de Disneyland.' },
      tip: 'Llega antes de la hora de apertura y descarga la app oficial de Disneyland antes del viaje: mapa, tiempos de espera y pedidos de comida en un solo lugar.',
      image: ['castle2013', 'castle2013b', 'castle2005'],
    },
    {
      date: '2026-10-13', dayNumber: 24, category: 'historia', scene: 'sunset',
      title: 'Palm Trees & Pink Hotels', theme: 'Las palmeras que alguien plantó',
      description: 'Nada dice “Los Ángeles” como una fila de palmeras contra el cielo naranja. Lo curioso es que casi ninguna es de ahí: son parte de un decorado que la ciudad se construyó a sí misma.',
      ...music('Hotel California', 'Eagles'),
      songWhy: 'La portada del disco es el Beverly Hills Hotel fotografiado al atardecer, entre palmeras. Misteriosa y dorada, como LA a esa hora.',
      fact: 'La gran mayoría de las palmeras de LA no son nativas: en los años 30 la ciudad plantó decenas de miles en sus calles, en parte como programa de empleo y de cara a los Juegos Olímpicos de 1932. La única palmera nativa de California es la Washingtonia filifera.',
      factSource: wiki('Washingtonia_filifera'),
      place: { name: 'Beverly Hills Hotel', area: 'Beverly Hills', note: 'El “Pink Palace”, abierto en 1912, famoso por su fachada rosada y su papel tapiz de hojas de plátano.', query: 'Beverly Hills Hotel' },
      movie: { title: 'Pretty Woman', year: 1990, note: 'Sus escenas de compras en Rodeo Drive, a pocas cuadras, volvieron a Beverly Hills un símbolo del cine.' },
      tip: 'Para la foto de palmeras infinitas, busca calles residenciales de Beverly Hills al atardecer, con el sol detrás de las copas.',
      image: [],
    },
    {
      date: '2026-10-14', dayNumber: 23, category: 'lugares', scene: 'skyline',
      title: 'Downtown LA', theme: 'El centro que volvió a despertar',
      description: 'Durante años, Downtown fue el lugar al que nadie iba de noche. Hoy mezcla rascacielos, teatros antiguos, mercados y arquitectura que parece de otro planeta. Es el LA que más cambia.',
      ...music('Under the Bridge', 'Red Hot Chili Peppers'),
      songWhy: 'Anthony Kiedis escribió sobre sentirse solo y encontrar compañía en la propia ciudad de Los Ángeles. Una de las canciones más honestas sobre LA.',
      fact: 'Angels Flight, el pequeño funicular de Bunker Hill, funciona desde 1901 y se presenta como “el ferrocarril más corto del mundo”: su recorrido mide unos 90 metros.',
      factSource: wiki('Angels_Flight'),
      place: { name: 'Walt Disney Concert Hall', area: 'Bunker Hill', note: 'La sala de conciertos de acero diseñada por Frank Gehry, inaugurada en 2003. Sus curvas brillan con el sol.', query: 'Walt Disney Concert Hall' },
      movie: { title: 'La La Land', year: 2016, note: 'Mia y Sebastian suben a Angels Flight en una de sus escenas. (500) Days of Summer también se filmó en esta zona.' },
      tip: 'Downtown se recorre a pie: Grand Central Market, Angels Flight, el Walt Disney Concert Hall y el museo The Broad están a pocas cuadras. The Broad tiene entrada general gratuita, pero conviene reservar.',
      image: [],
    },
    {
      date: '2026-10-15', dayNumber: 22, category: 'viaje', scene: 'road',
      title: 'Route 66 Turns 100', theme: 'El final de la Ruta Madre',
      description: 'Durante décadas, llegar a California por carretera significaba una cosa: la Ruta 66. Y vas a llegar a LA justo el año de su centenario.',
      ...music('Route 66', 'Chuck Berry'),
      songWhy: 'Bobby Troup la escribió en 1946 mientras manejaba de Pensilvania a Los Ángeles por esta ruta. Nat King Cole tuvo el primer éxito con ella; la versión de Chuck Berry le puso motor de rock and roll.',
      fact: 'La Ruta 66 se creó el 11 de noviembre de 1926 y unía Chicago con Santa Mónica. John Steinbeck la llamó “la Ruta Madre” en Las uvas de la ira. Cumple 100 años en noviembre de 2026, días después de tu llegada.',
      factSource: wiki('U.S._Route_66'),
      place: { name: 'Muelle de Santa Mónica', area: 'Santa Mónica', note: 'Ahí está el letrero “Santa Monica 66, End of the Trail”, el final simbólico de la ruta.', query: 'Route 66 End of the Trail sign Santa Monica Pier' },
      movie: { title: 'The Grapes of Wrath', year: 1940, note: 'John Ford adaptó la novela de Steinbeck: una familia cruza el país por la Ruta 66 rumbo a California.' },
      tip: 'Foto obligada: el letrero “End of the Trail” en el muelle de Santa Mónica. Llega temprano si la quieres sin multitud.',
      image: ['route66'],
    },
    {
      date: '2026-10-16', dayNumber: 21, category: 'musica', scene: 'neon',
      title: 'Capitol Records', theme: 'La torre que suena',
      description: 'En Hollywood y Vine hay un edificio redondo que parece una pila de discos. Adentro se grabaron voces que definieron el siglo XX.',
      ...music('Unforgettable', 'Nat King Cole'),
      songWhy: 'Nat King Cole vendió tantos discos para Capitol que a la torre la llaman “la casa que construyó Nat”.',
      fact: 'La torre de Capitol Records se terminó en 1956 y fue el primer edificio de oficinas circular del mundo. La luz de su antena parpadea la palabra “Hollywood” en código Morse.',
      factSource: wiki('Capitol_Records_Building'),
      place: { name: 'Hollywood y Vine', area: 'Hollywood', note: 'Cruce histórico de Hollywood, donde se juntan la torre de Capitol y las estrellas del Paseo de la Fama.', query: 'Capitol Records Building' },
      movie: null,
      tip: 'Mira la torre desde Vine Street al anochecer, cuando se enciende la luz de la antena.',
      image: [],
    },
    {
      date: '2026-10-17', dayNumber: 20, category: 'costa', scene: 'pier',
      title: 'Día Santa Monica', theme: 'El muelle al final del mapa',
      description: 'Una noria encendida sobre el mar, olor a algodón de azúcar y el Pacífico debajo de tus pies. El muelle de Santa Mónica es la postal más feliz de LA.',
      story: 'Imagina llegar caminando por Ocean Avenue, entre palmeras, y bajar la rampa hacia el muelle cuando el sol ya está bajo. La noria empieza a encender sus luces, el mar se pone dorado y entiendes por qué la Ruta 66 decidió terminar justo aquí.',
      ...music('Santa Monica', 'Everclear'),
      songWhy: 'Un himno de los 90 sobre escapar hacia el mar y empezar de nuevo. Lleva el nombre del lugar y su mismo espíritu.',
      fact: 'El muelle abrió en 1909. Su carrusel, el Looff Hippodrome de 1916, aparece en la película The Sting (1973), y la noria de Pacific Park funciona con energía solar.',
      factSource: wiki('Santa_Monica_Pier'),
      place: { name: 'Pacific Park', area: 'Muelle de Santa Mónica', note: 'El parque de diversiones sobre el muelle, con su noria y su montaña rusa frente al océano.', query: 'Pacific Park Santa Monica Pier' },
      movie: { title: 'Forrest Gump', year: 1994, note: 'Forrest termina su primera gran carrera hasta el Pacífico justo en este muelle.' },
      tip: 'A inicios de noviembre el sol se pone cerca de las 5:00 p. m. Llega unos 45 minutos antes: la luz dorada sobre la noria es el mejor momento.',
      image: ['ferrisWheel'],
    },
    {
      date: '2026-10-18', dayNumber: 19, category: 'parques', scene: 'lights',
      title: 'Día Universal', theme: 'Detrás de la pantalla',
      description: 'Universal Studios Hollywood es parque de diversiones y estudio de cine funcionando al mismo tiempo. Puedes subirte a una atracción y, media hora después, pasar en tranvía junto a un set real.',
      story: 'Imagina el Studio Tour: el tranvía baja por la colina, pasa por calles falsas que has visto en mil películas y, en lo alto de una loma, aparece la casa de Psycho. Ahí entiendes que Hollywood también es un lugar de trabajo.',
      ...music('The Power of Love', 'Huey Lewis & The News'),
      songWhy: 'Es la canción de Back to the Future, cuya plaza del reloj, Courthouse Square, está en el backlot de Universal. Llegó al número uno en 1985.',
      fact: 'En 1915, Carl Laemmle abrió Universal City y cobraba 25 centavos a los visitantes que querían ver filmaciones. El famoso tour en tranvía empezó en 1964.',
      factSource: wiki('Universal_Studios_Hollywood'),
      place: { name: 'Studio Tour', area: 'Universal City', note: 'El recorrido en tranvía por el backlot, con sets como la casa de Psycho y la plaza de Back to the Future.', query: 'Universal Studios Hollywood' },
      movie: { title: 'Psycho', year: 1960, note: 'La casa y el motel Bates siguen en el backlot y son parte del recorrido.' },
      tip: 'Haz el Studio Tour temprano, antes de las filas largas. Upper Lot y Lower Lot se conectan por escaleras eléctricas larguísimas: calcula tiempo para moverte.',
      image: ['psycho'],
    },
    {
      date: '2026-10-19', dayNumber: 18, category: 'cine', scene: 'lights',
      title: 'The Chinese Theatre', theme: 'Manos en el cemento',
      description: 'Frente a este cine, las estrellas dejan sus manos y sus pies en cemento fresco. Es una tradición de casi un siglo y, todavía, un sitio de estrenos.',
      ...music('Star Wars (Main Title)', 'John Williams', 'Star Wars Main Title John Williams'),
      songWhy: 'En 1977 Star Wars se estrenó en este teatro y las filas daban la vuelta a la cuadra. Ese mismo año, C-3PO, R2-D2 y Darth Vader dejaron sus huellas en el patio.',
      fact: 'El teatro abrió en 1927 y su patio guarda las huellas de unas 200 estrellas del cine. Entre 1944 y 1946 fue sede de la ceremonia de los Oscar.',
      factSource: wiki('TCL_Chinese_Theatre'),
      place: { name: 'TCL Chinese Theatre', area: 'Hollywood Boulevard', note: 'El patio de las huellas es gratis y está abierto al público; el cine sigue proyectando películas.', query: 'TCL Chinese Theatre' },
      movie: { title: 'Star Wars', year: 1977, note: 'Una de las salas de su estreno original y una de las más recordadas por los fans.' },
      tip: 'Compara tus manos con las de tus actores favoritos: es el pasatiempo oficial del patio y no cuesta nada.',
      image: [],
    },
    {
      date: '2026-10-20', dayNumber: 17, category: 'costa', scene: 'sunset',
      title: 'Venice', theme: 'Canales junto al Pacífico',
      description: 'Venice es el LA más bohemio: patinadores, murales, músicos callejeros, gimnasio al aire libre y, a dos cuadras, canales tranquilos que parecen de otro continente.',
      ...music('Good Vibrations', 'The Beach Boys'),
      songWhy: 'Brian Wilson la grabó durante meses en varios estudios de Los Ángeles. Es el sonido de la costa en su versión más experimental, como Venice.',
      fact: 'Abbot Kinney fundó “Venice of America” en 1905, con canales inspirados en Venecia. En 1929 la mayoría se rellenó para hacer calles; los que sobreviven forman hoy un barrio histórico.',
      factSource: wiki('Venice,_Los_Angeles'),
      place: { name: 'Venice Canals', area: 'Venice', note: 'Puentecitos peatonales, casas con jardín y patos, a pocos minutos del boardwalk.', query: 'Venice Canals Los Angeles' },
      movie: { title: 'Lords of Dogtown', year: 2005, note: 'Cuenta la historia real de los Z-Boys, los skaters de Venice y Santa Mónica que cambiaron el skateboarding en los 70.' },
      tip: 'Camina los canales a media tarde y vuelve al boardwalk para el atardecer: el contraste entre ambos es lo mejor de Venice.',
      image: ['veniceTower'],
    },
    {
      date: '2026-10-21', dayNumber: 16, category: 'lugares', scene: 'sunset',
      title: 'The Getty', theme: 'Un museo en la colina',
      description: 'Un tranvía sube la colina y arriba aparece un museo blanco con jardines y vista al océano. El Getty es el lugar ideal para bajarle el volumen a la ciudad.',
      ...music('Sunset Lover', 'Petit Biscuit'),
      songWhy: 'Un instrumental de atardecer, sin prisa, perfecto para la luz dorada que pega en las terrazas del Getty al final del día.',
      fact: 'El Getty Center abrió en 1997 y lo diseñó Richard Meier. La piedra beige que lo cubre es travertino de Bagni di Tivoli, en Italia, la misma zona de donde salió la piedra del Coliseo romano.',
      factSource: wiki('Getty_Center'),
      place: { name: 'Getty Center', area: 'Brentwood', note: 'Arte europeo, jardines y miradores a la ciudad y al Pacífico.', query: 'Getty Center' },
      movie: null,
      tip: 'La entrada al Getty Center es gratuita (se paga el parqueo). Un tranvía sin conductor te sube desde la base de la colina.',
      image: [],
    },
    {
      date: '2026-10-22', dayNumber: 15, category: 'sabores', scene: 'road',
      title: 'Drive-Thru Nation', theme: 'Una ciudad que vive en el carro',
      description: 'LA se organizó alrededor del automóvil: autocinemas, lowriders, autopistas y comida que te entregan por la ventana. Hasta las hamburguesas se pensaron para no bajarte del carro.',
      ...music('Low Rider', 'War'),
      songWhy: 'War, una banda de Long Beach, le dedicó esta canción en 1975 a la cultura lowrider, nacida en los barrios mexicoamericanos del sur de California.',
      fact: 'In-N-Out abrió en 1948 en Baldwin Park, en el condado de LA, como el primer autoservicio de hamburguesas de California con altavoz de dos vías: pedías desde el carro, sin bajarte.',
      factSource: wiki('In-N-Out_Burger'),
      place: { name: 'Petersen Automotive Museum', area: 'Miracle Mile', note: 'Museo de autos en Wilshire Boulevard, con una fachada roja de cintas de acero imposible de ignorar.', query: 'Petersen Automotive Museum' },
      movie: null,
      tip: 'El In-N-Out de Sepulveda Boulevard, junto a LAX, es famoso porque los aviones pasan bajísimo mientras comes. Pide tu hamburguesa “Animal Style”, del menú no tan secreto.',
      image: ['amboy'],
    },
    {
      date: '2026-10-23', dayNumber: 14, category: 'lugares', scene: 'observatory',
      title: 'Mulholland Drive', theme: 'Dos semanas: la ciudad desde arriba',
      milestone: { key: '14', label: 'Two Weeks', message: 'Dos semanas. Ya no es “algún día”: es dentro de dos viernes.' },
      description: 'Mulholland Drive serpentea por la cresta de las colinas de Hollywood. De un lado, el Valle; del otro, la cuenca de LA. De noche, las dos se vuelven un mar de luces.',
      story: 'Faltan catorce días. Imagina detenerte en un mirador de Mulholland justo cuando cae la noche: abajo, millones de luces se encienden una a una, como si la ciudad también estuviera contando.',
      ...music('Free Fallin’', 'Tom Petty'),
      songWhy: 'Es la canción de las colinas de LA por excelencia: menciona Mulholland y Ventura Boulevard, y suena a manejar de noche con las ventanas abiertas.',
      fact: 'La calle lleva el nombre de William Mulholland, el ingeniero que construyó el acueducto de Los Ángeles, inaugurado en 1913 para traer agua desde el valle de Owens.',
      factSource: wiki('Mulholland_Drive'),
      place: { name: 'Hollywood Bowl Overlook', area: 'Mulholland Drive', note: 'Mirador sobre el Hollywood Bowl con vista a la cuenca de LA.', query: 'Hollywood Bowl Overlook Mulholland Drive' },
      movie: { title: 'Mulholland Drive', year: 2001, note: 'David Lynch convirtió esta calle en el título de su película más misteriosa sobre Hollywood.' },
      tip: 'Mulholland tiene curvas estrechas y poca iluminación. Si vas de noche, que maneje alguien que conozca la ruta y detente solo en miradores oficiales.',
      image: ['panorama'],
    },
    {
      date: '2026-10-24', dayNumber: 13, category: 'parques', scene: 'fireworks',
      title: 'Día California Adventure', theme: 'El parque que celebra California',
      description: 'Frente a Disneyland hay otro parque dedicado a California: su historia, su cine, su costa y hasta su carretera más famosa. De noche, Cars Land se enciende como un pueblo de la Ruta 66.',
      story: 'Imagina entrar por Buena Vista Street, una recreación del LA de los años 20, y caminar hasta Cars Land. Detrás de las montañas de roca roja corre Radiator Springs Racers. Cuando cae el sol, el neón del pueblo se enciende al mismo tiempo, con música de los 50.',
      ...music('Life Is a Highway', 'Rascal Flatts'),
      songWhy: 'Es la versión que suena en Cars (2006), la película que inspiró Cars Land. La original es de Tom Cochrane, de 1991.',
      fact: 'Disney California Adventure abrió el 8 de febrero de 2001 en el terreno que antes era el parqueo de Disneyland. Cars Land, inspirada en la Ruta 66, se inauguró en 2012.',
      factSource: wiki('Disney_California_Adventure'),
      place: { name: 'Buena Vista Street', area: 'Disney California Adventure', note: 'Su teatro Carthay Circle recuerda al cine real donde se estrenó Blancanieves en 1937.', query: 'Disney California Adventure Park' },
      movie: { title: 'Cars', year: 2006, note: 'Radiator Springs, el pueblo de la película, está inspirado en pueblos reales de la Ruta 66.' },
      tip: 'Quédate en Cars Land al anochecer: el momento en que se enciende el neón de Radiator Springs es de los mejores del parque.',
      image: [],
    },
    {
      date: '2026-10-25', dayNumber: 12, category: 'cine', scene: 'lights',
      title: 'Hollywood', theme: 'La fábrica de sueños',
      description: 'Hollywood es un barrio, una industria y una idea a la vez. Hoy toca la idea: por qué un pueblo de huertos se convirtió en la capital del cine.',
      story: 'A principios del siglo XX, los cineastas llegaron al sur de California por el sol, que dejaba filmar casi todo el año, y por la variedad de paisajes a pocas horas: desierto, montaña, playa y ciudad. En pocos años, Hollywood dejó de ser un pueblo y se volvió sinónimo de película.',
      ...music('City of Stars', 'Ryan Gosling & Emma Stone'),
      songWhy: 'Ganó el Oscar a mejor canción original en 2017 y es una carta de amor a la ciudad de las estrellas. Sebastian la canta en el muelle de Hermosa Beach.',
      fact: 'La primera ceremonia de los Oscar se hizo el 16 de mayo de 1929 en el Hotel Hollywood Roosevelt y duró unos 15 minutos. Desde 2002, la ceremonia se celebra en el Dolby Theatre, a pasos de ese hotel.',
      factSource: wiki('1st_Academy_Awards'),
      place: { name: 'Hollywood y Highland', area: 'Hollywood Boulevard', note: 'En un par de cuadras se juntan el Dolby Theatre, el TCL Chinese Theatre y el Hotel Roosevelt.', query: 'Dolby Theatre Hollywood' },
      movie: { title: 'Once Upon a Time in Hollywood', year: 2019, note: 'Quentin Tarantino transformó Hollywood Boulevard para recrear cómo se veía en 1969.' },
      list: { title: 'Four Stops', items: ['Dolby Theatre, la casa de los Oscar', 'TCL Chinese Theatre y sus huellas', 'El Paseo de la Fama, hacia el este', 'La torre de Capitol Records, en Vine'] },
      tip: 'Hollywood Boulevard es intensa: personajes disfrazados piden propina por las fotos y hay vendedores de tours. Decide antes qué quieres ver y camina con calma.',
      image: ['hollywood1922'],
    },
    {
      date: '2026-10-26', dayNumber: 11, category: 'musica', scene: 'lights',
      title: 'Hollywood Bowl', theme: 'Música bajo las estrellas',
      description: 'Un anfiteatro en una hondonada natural de las colinas, con su concha de arcos concéntricos al fondo. Desde 1922, LA escucha música al aire libre aquí.',
      ...music('A Hard Day’s Night', 'The Beatles', 'A Hard Day’s Night The Beatles Live at the Hollywood Bowl'),
      songWhy: 'The Beatles tocaron en el Hollywood Bowl en 1964 y 1965; esas grabaciones se convirtieron en su disco en vivo en el Bowl, publicado en 1977.',
      fact: 'El Hollywood Bowl presentó su primera temporada en 1922 y es uno de los anfiteatros naturales más grandes de Estados Unidos, con capacidad para unas 17.500 personas.',
      factSource: wiki('Hollywood_Bowl'),
      place: { name: 'Hollywood Bowl', area: 'Hollywood Hills', note: 'Su temporada fuerte va de la primavera al otoño: revisa si hay algo programado durante tu viaje.', query: 'Hollywood Bowl' },
      movie: null,
      tip: 'En muchos conciertos del Bowl se permite llevar picnic: es parte de la tradición. Revisa las reglas de cada evento antes de ir.',
      image: ['starLennon'],
    },
    {
      date: '2026-10-27', dayNumber: 10, category: 'sabores', scene: 'sunset',
      title: 'Brunch in the Sun', theme: 'Sabores de California',
      description: 'California come distinto: aguacate en todo, mercados al aire libre y platos que nacieron en restaurantes de Hollywood. Hoy el viaje se saborea.',
      ...music('Island in the Sun', 'Weezer'),
      songWhy: 'Weezer se formó en Los Ángeles en 1992, y esta canción suena a domingo de sol sin nada que hacer.',
      fact: 'El aguacate Hass, el más vendido del mundo, nació en La Habra Heights, en el condado de LA: Rudolph Hass lo patentó en 1935. La ensalada Cobb también es angelina: se inventó en el restaurante Brown Derby de Hollywood en los años 30.',
      factSource: wiki('Hass_avocado'),
      place: { name: 'Original Farmers Market', area: '3rd Street y Fairfax', note: 'Mercado abierto desde 1934, con puestos de comida de todo tipo y su torre del reloj.', query: 'Original Farmers Market Los Angeles' },
      movie: null,
      tip: 'En el Farmers Market puedes almorzar picando de puesto en puesto; al lado está The Grove, un centro comercial al aire libre.',
      image: [],
    },
    {
      date: '2026-10-28', dayNumber: 9, category: 'viaje', scene: 'flight',
      title: 'LAX', theme: 'La puerta de entrada',
      description: 'Tres letras que vas a ver en tu pase de abordar. LAX es uno de los aeropuertos más transitados del mundo y, para ti, va a ser la primera escena de la película.',
      ...music('Jet Airliner', 'Steve Miller Band'),
      songWhy: 'Una canción de 1977 sobre subirse a un avión y dejar atrás lo conocido. La escribió Paul Pena y Steve Miller la convirtió en clásico de carretera, y de aeropuerto.',
      fact: 'La X de LAX no significa nada. El aeropuerto usaba el código “LA” y, cuando los códigos pasaron a tener tres letras, le agregaron una X. Abrió en 1928 como Mines Field.',
      factSource: wiki('Los_Angeles_International_Airport'),
      place: { name: 'Theme Building', area: 'LAX', note: 'El edificio con forma de nave espacial en el centro del aeropuerto, de 1961: un ícono de la arquitectura de la era espacial.', query: 'Theme Building LAX' },
      movie: null,
      tip: 'Guarda la dirección de tu primer alojamiento en el teléfono y en papel: en migración pueden preguntarte dónde te vas a quedar.',
      image: [],
    },
    {
      date: '2026-10-29', dayNumber: 8, category: 'historia', scene: 'mammoth',
      title: 'La Brea Tar Pits', theme: 'La Edad de Hielo en Wilshire',
      description: 'En medio de la ciudad, entre museos y oficinas, hay pozos de asfalto natural donde quedaron atrapados mamuts y tigres dientes de sable. LA tiene su propio parque prehistórico.',
      ...music('Walking in L.A.', 'Missing Persons'),
      songWhy: 'Un clásico new wave de 1982 que se burla de que en LA nadie camina. Museum Row, donde están los pozos de brea, es de las pocas zonas hechas para recorrer a pie.',
      fact: '“La Brea” significa “el alquitrán” en español, así que “La Brea Tar Pits” quiere decir, literalmente, “los pozos de alquitrán del alquitrán”. De ahí han salido fósiles de la Edad de Hielo como el tigre dientes de sable, que es el fósil oficial de California.',
      factSource: wiki('La_Brea_Tar_Pits'),
      place: { name: 'La Brea Tar Pits and Museum', area: 'Hancock Park, Miracle Mile', note: 'Hay pozos burbujeantes al aire libre y un museo con esqueletos completos.', query: 'La Brea Tar Pits and Museum' },
      movie: { title: 'Volcano', year: 1997, note: 'En esta película de desastres, un volcán hace erupción justamente desde los pozos de La Brea.' },
      tip: 'La Brea Tar Pits, el museo LACMA y su instalación Urban Light están en la misma zona de Wilshire Boulevard. Combínalos en una tarde y quédate hasta que se enciendan los faroles.',
      image: [],
    },
    {
      date: '2026-10-30', dayNumber: 7, category: 'musica', scene: 'fireworks',
      title: 'One Week', theme: 'Siete días, siete escenas',
      milestone: { key: '7', label: 'One Week', message: 'Una semana. Desde hoy, cada día que se abre aquí es uno menos para despegar.' },
      description: 'Siete días es la distancia exacta de un viernes al siguiente, y el viernes siguiente estás volando. Hoy, en lugar de un lugar, siete momentos para esperar.',
      ...music('California Love', '2Pac ft. Dr. Dre'),
      songWhy: 'Si hay una canción que suena a llegar a California en grande, es esta. Su video, inspirado en Mad Max Beyond Thunderdome, imagina una fiesta en un desierto futurista.',
      fact: 'Los Ángeles organizó los Juegos Olímpicos de 1932 y 1984, y volverá a hacerlo en 2028. El LA Memorial Coliseum fue sede de los dos primeros y también está previsto para el tercero.',
      factSource: wiki('Los_Angeles_Memorial_Coliseum'),
      place: { name: 'LA Memorial Coliseum', area: 'Exposition Park', note: 'El estadio olímpico de LA, junto al Exposition Park y sus museos.', query: 'Los Angeles Memorial Coliseum' },
      movie: null,
      list: { title: 'The Seven', items: ['La primera vez que veas palmeras desde la ventana del avión.', 'El primer atardecer en el Pacífico, con la noria encendida.', 'Cruzar el castillo de Disneyland hacia Fantasyland.', 'El tranvía del Studio Tour pasando junto a la casa de Psycho.', 'La ciudad completa desde las terrazas de Griffith.', 'Encontrar una estrella con un nombre que te importe.', 'Esa noche en que no vas a querer volver al hotel.'] },
      tip: 'Esta semana: descarga los mapas de LA para usarlos sin conexión, confirma reservas y define cómo vas a tener datos en el teléfono (roaming o eSIM).',
      image: [],
    },
    {
      date: '2026-10-31', dayNumber: 6, category: 'cine', scene: 'neon',
      title: 'Halloween in LA', theme: 'La noche más cinematográfica',
      description: 'En la ciudad del cine, Halloween es casi un estreno: disfraces dignos de producción, calles enteras de fiesta y una película de terror que se filmó a pocos kilómetros.',
      ...music('Thriller', 'Michael Jackson'),
      songWhy: 'El video de Thriller se filmó en Los Ángeles; la escena del cine se grabó en el Palace Theatre, en el centro de la ciudad.',
      fact: 'La película Halloween (1978), de John Carpenter, se filmó en South Pasadena, al noreste del centro de LA, que hizo de un pueblo ficticio de Illinois.',
      factSource: wiki('Halloween_(1978_film)'),
      place: { name: 'Distrito de teatros de Broadway', area: 'Downtown LA', note: 'Una docena de cines y teatros históricos con marquesinas iluminadas, entre ellos el Palace Theatre.', query: 'Palace Theatre Broadway Los Angeles' },
      movie: { title: 'Halloween', year: 1978, note: 'Se rodó en primavera, con hojas secas falsas para fingir el otoño de octubre.' },
      tip: 'Si pasas por Broadway, en Downtown, mira hacia arriba: las marquesinas de los teatros históricos son de las más bonitas de la ciudad.',
      image: [],
    },
    {
      date: '2026-11-01', dayNumber: 5, category: 'viaje', scene: 'sunset',
      title: 'Fall Back', theme: 'Hoy LA cambia de hora',
      description: 'Esta madrugada terminó el horario de verano en Estados Unidos: los relojes de LA retrocedieron una hora. Desde hoy, Los Ángeles va dos horas detrás de Costa Rica.',
      ...music('Hold On', 'Wilson Phillips'),
      songWhy: 'Wilson Phillips son las hijas de Brian Wilson (Beach Boys) y de John y Michelle Phillips (The Mamas & the Papas): la realeza musical de California. Y el título es el mensaje del día: aguanta, ya casi.',
      fact: 'En Estados Unidos, el horario de verano termina el primer domingo de noviembre a las 2:00 a. m. Costa Rica no usa horario de verano, así que la diferencia con LA pasa de una a dos horas.',
      factSource: wiki('Daylight_saving_time_in_the_United_States'),
      place: { name: 'Union Station', area: 'Downtown LA', note: 'La estación de tren de 1939, con su torre del reloj y su sala de espera art déco.', query: 'Union Station Los Angeles' },
      movie: { title: 'Blade Runner', year: 1982, note: 'El vestíbulo de Union Station aparece como la estación de policía de la película.' },
      tip: 'Si aterrizas de noche, tu cuerpo va a sentir que es más tarde de lo que marca el reloj de LA. Planea una cena ligera y dormir temprano el primer día.',
      image: [],
    },
    {
      date: '2026-11-02', dayNumber: 4, category: 'historia', scene: 'marigold',
      title: 'Día de los Muertos', theme: 'Donde empezó Los Ángeles',
      description: 'Hoy LA se llena de cempasúchil, papel picado y altares. Y una de las celebraciones más bonitas sucede justo donde nació la ciudad, en español.',
      ...music('La Bamba', 'Los Lobos'),
      songWhy: 'Los Lobos, del Este de Los Ángeles, llevaron este son jarocho al número uno en 1987 con la película sobre Ritchie Valens, el muchacho de Pacoima que la volvió rock and roll.',
      fact: 'Los Ángeles se fundó el 4 de septiembre de 1781 como El Pueblo de la Reina de los Ángeles. Lo fundaron 44 pobladores de origen indígena, africano y europeo, llegados del noroeste de México.',
      factSource: wiki('History_of_Los_Angeles'),
      place: { name: 'Olvera Street', area: 'El Pueblo de Los Ángeles', note: 'El corazón histórico de la ciudad, con mercado mexicano y el Avila Adobe de 1818, la casa más antigua que sigue en pie en LA.', query: 'Olvera Street Los Angeles' },
      movie: { title: 'La Bamba', year: 1987, note: 'La biografía de Ritchie Valens, con música de Los Lobos.' },
      tip: 'Prueba los taquitos con salsa de aguacate de Cielito Lindo, en Olvera Street desde 1934.',
      image: [],
    },
    {
      date: '2026-11-03', dayNumber: 3, category: 'viaje', scene: 'flight',
      title: 'La Maleta', theme: 'Tres días: hora de empacar',
      milestone: { key: '3', label: '3 Days', message: 'Tres días. La maleta deja de ser una idea y se vuelve un objeto en tu cuarto.' },
      description: 'Faltan tres días y la emoción empieza a tener forma de lista. Hoy no hay museos: hoy toca empacar bien.',
      ...music('Come Fly with Me', 'Frank Sinatra'),
      songWhy: 'La invitación más elegante jamás grabada para subirse a un avión. Sinatra la grabó en 1957 para Capitol Records, la de la torre redonda de Hollywood.',
      fact: 'Entre el aeropuerto Juan Santamaría y LAX hay unos 4.380 km en línea recta. El aeropuerto de salida lleva el nombre del héroe nacional de Costa Rica.',
      factSource: null,
      factNote: 'Distancia calculada con las coordenadas de SJO y LAX.',
      place: { name: 'Aeropuerto Juan Santamaría (SJO)', area: 'Alajuela, Costa Rica', note: 'El punto de partida del viaje.', query: 'Aeropuerto Internacional Juan Santamaría' },
      movie: null,
      list: { title: 'The Checklist', items: ['Pasaporte y visa vigentes', 'Pase de abordar en el teléfono y una copia', 'Dirección del alojamiento a mano', 'Cargador y batería portátil', 'Zapatos cómodos: vas a caminar muchísimo', 'Una chaqueta ligera para las noches', 'Lentes de sol y bloqueador', 'Líquidos de mano en envases de máximo 100 ml'] },
      tip: 'Costa Rica y Estados Unidos usan los mismos enchufes (tipos A y B) y el mismo voltaje, 120 V: no necesitas adaptador.',
      image: [],
    },
    {
      date: '2026-11-04', dayNumber: 2, category: 'musica', scene: 'skyline',
      title: 'LA After Dark', theme: 'Dos días: la ciudad de noche',
      milestone: { key: '2', label: '2 Days', message: 'Dos noches más. Ya casi puedes ver la ciudad encendida desde la ventana del avión.' },
      description: 'Los Ángeles de noche es otra ciudad: autopistas que parecen ríos de luz, neón, puentes iluminados y un cielo naranja que nunca termina de oscurecer.',
      ...music('Nightcall', 'Kavinsky'),
      songWhy: 'Abre la película Drive (2011) con un carro cruzando LA de noche. Sintetizadores, luces de autopista y suspenso: la ciudad en su versión más cinematográfica.',
      fact: 'El intercambio Four Level, en el centro de LA, se abrió en 1953 y fue el primer intercambio de autopistas apiladas del mundo.',
      factSource: wiki('Four_Level_Interchange'),
      place: { name: 'Sixth Street Viaduct', area: 'Arts District y Boyle Heights', note: 'El puente nuevo sobre el río de Los Ángeles, inaugurado en 2022, con arcos que se iluminan de noche.', query: 'Sixth Street Viaduct Los Angeles' },
      movie: { title: 'Drive', year: 2011, note: 'LA de noche como protagonista. Y si te gusta el río de concreto, Grease (1978) y Terminator 2 (1991) filmaron persecuciones en el cauce del río de Los Ángeles.' },
      tip: 'Si aterrizas de noche, mira por la ventana durante la aproximación: LA aparece como una cuadrícula de luces que parece no terminar.',
      image: [],
    },
    {
      date: '2026-11-05', dayNumber: 1, category: 'viaje', scene: 'lights',
      title: 'Tomorrow', theme: 'La última noche de espera',
      milestone: { key: '1', label: 'Tomorrow', message: 'Mañana. Esta es la última página antes del viaje.' },
      description: 'Treinta y cinco días después, solo queda una noche. Mañana la cuenta regresiva se convierte en viaje.',
      story: 'Imagina el final de mañana: la ciudad apareciendo bajo el avión como un tablero de luces, el aire tibio al salir del aeropuerto, las palmeras recortadas contra el cielo. Todo lo que viste aquí durante 35 días está a punto de pasar de la pantalla a la realidad.',
      ...music('Another Day of Sun', 'La La Land Cast'),
      songWhy: 'Abre La La Land con decenas de personas que llegaron a LA con un sueño en la maleta. Se filmó en una rampa real de autopista, la del intercambio entre la 105 y la 110.',
      fact: 'En LAX los aviones aterrizan casi siempre hacia el oeste, de cara al océano, porque el viento suele soplar desde el mar. Por eso la aproximación final pasa sobre la ciudad.',
      factSource: wiki('Los_Angeles_International_Airport'),
      place: { name: 'LAX', area: 'Westchester, Los Ángeles', note: 'Tu primera escena en LA.', query: 'Los Angeles International Airport' },
      movie: { title: 'La La Land', year: 2016, note: 'Empieza en un embotellamiento de autopista y termina siendo una carta de amor a la ciudad.' },
      tip: 'Hoy: check-in en línea, doble alarma, documentos en la mochila de mano y el teléfono cargado. Y duerme: mañana empieza todo.',
      image: [],
    },
    {
      date: '2026-11-06', dayNumber: 0, category: 'viaje', scene: 'fireworks',
      title: 'The Day', theme: 'Road to LA is over. The adventure begins.',
      milestone: { key: '0', label: 'Today', message: 'Hoy es el día. Road to LA terminó: empieza Los Ángeles.' },
      description: 'Treinta y cinco días de canciones, lugares y datos llevaban a este momento. Ya no hay que imaginar nada: hoy Los Ángeles deja de ser una pantalla.',
      ...music('I Love L.A.', 'Randy Newman'),
      songWhy: 'Es el himno oficioso de la ciudad: suena en el estadio de los Dodgers cada vez que ganan. Hoy ganaste tú.',
      fact: 'Desde el 1 de noviembre, Los Ángeles va dos horas detrás de Costa Rica. Cuando aterrices, ajusta el reloj: el día te va a rendir dos horas más.',
      factSource: wiki('Pacific_Time_Zone'),
      place: { name: 'Los Ángeles', area: 'California', note: 'Todo lo de los últimos 35 días, ahora a tu alcance.', query: 'Los Angeles' },
      movie: null,
      list: { title: 'First Things', items: ['Mirar por la ventana en la aproximación', 'Ajustar la hora del teléfono: dos horas menos', 'Tomar agua y comer algo ligero', 'La primera foto con palmeras', 'Escuchar I Love L.A. camino al hotel'] },
      tip: 'Date permiso de solo mirar el primer día. La ciudad no se va a ir a ninguna parte.',
      image: ['signWolf'],
    },
  ];

  // ---------------------------------------------------------------------------
  // MY LA TRIP: los seis lugares del viaje.
  // ---------------------------------------------------------------------------
  const TRIP_PLACES = [
    {
      id: 'disneyland', name: 'Disneyland', area: 'Anaheim, condado de Orange', day: '2026-10-12', scene: 'fireworks',
      text: 'El parque original de Disney, abierto en 1955: Main Street, el castillo y Fantasyland.',
      fact: 'Es el único parque de Disney que Walt Disney vio construir y caminó en persona.',
      image: ['castle2013', 'castle2013b', 'castle2005'], maps: 'Disneyland Park, Anaheim', url: 'https://disneyland.disney.go.com/',
    },
    {
      id: 'california-adventure', name: 'Disney California Adventure', area: 'Anaheim, condado de Orange', day: '2026-10-24', scene: 'fireworks',
      text: 'El parque vecino, dedicado a California: Cars Land, Pixar Pier y Buena Vista Street.',
      fact: 'Abrió en 2001 sobre el antiguo parqueo de Disneyland.',
      image: [], maps: 'Disney California Adventure Park, Anaheim', url: 'https://disneyland.disney.go.com/',
    },
    {
      id: 'universal', name: 'Universal Studios Hollywood', area: 'Universal City', day: '2026-10-18', scene: 'lights',
      text: 'Parque temático dentro de un estudio de cine que sigue funcionando.',
      fact: 'El Studio Tour en tranvía existe desde 1964.',
      image: ['psycho'], maps: 'Universal Studios Hollywood', url: 'https://www.universalstudioshollywood.com/',
    },
    {
      id: 'griffith', name: 'Griffith Observatory', area: 'Griffith Park, Los Feliz', day: '2026-10-08', scene: 'observatory',
      text: 'Telescopios, planetario y la mejor vista de la ciudad.',
      fact: 'La entrada al edificio es gratuita; cierra los lunes.',
      image: ['griffith'], maps: 'Griffith Observatory', url: 'https://griffithobservatory.org/',
    },
    {
      id: 'walk-of-fame', name: 'Hollywood Walk of Fame', area: 'Hollywood Boulevard y Vine Street', day: '2026-10-10', scene: 'lights',
      text: 'Más de 2.700 estrellas en las aceras de Hollywood.',
      fact: 'Gene Autry es el único con estrellas en las cinco categorías.',
      image: ['starCooper', 'starStewart'], maps: 'Hollywood Walk of Fame', url: 'https://walkoffame.com/',
    },
    {
      id: 'santa-monica', name: 'Santa Monica Pier', area: 'Santa Mónica', day: '2026-10-17', scene: 'pier',
      text: 'La noria sobre el mar, Pacific Park y el final de la Ruta 66.',
      fact: 'Abrió en 1909; su carrusel es de 1916.',
      image: ['ferrisWheel'], maps: 'Santa Monica Pier', url: 'https://www.santamonicapier.org/',
    },
  ];

  const dayIndex = (iso) => {
    const [y, m, d] = iso.split('-').map(Number);
    return Math.round(Date.UTC(y, m - 1, d) / 86400000);
  };

  // Texto de la notificación diaria. Lo usan la app, el service worker y el script de GitHub Actions.
  function notificationFor(isoDate) {
    const n = dayIndex(CONFIG.departureDate) - dayIndex(isoDate);
    const total = dayIndex(CONFIG.departureDate) - dayIndex(CONFIG.startDate);
    if (!(n >= 0 && n <= total)) return null;
    const url = './#today';
    if (n === 0) return { title: 'ROAD TO LA', body: 'Hoy es el día. Road to LA terminó: empieza la aventura.', url };
    if (n === 1) return { title: 'ROAD TO LA', body: 'Mañana: Los Ángeles. Abre la última página antes del viaje.', url };
    return { title: 'ROAD TO LA', body: `Quedan ${n} días. Descubre la canción y curiosidad de hoy.`, url };
  }

  root.ROAD_TO_LA = Object.freeze({ CONFIG, CATEGORIES, PHOTOS, TRIP_PLACES, countdownDays, notificationFor, dayIndex });
})(typeof globalThis !== 'undefined' ? globalThis : self);
